### ISSUE TITLE
Disabling battery icon puts device in safe mode

### ISSUE THREAD

**Issue by cln-b** [NoisyFlake/iPadStatusBar#1]
If I disable the battery icon, my phone gets stuck in a safe mode loop and have to re-enable it in the .plist file through filza. (iPhone 6s, 12.4)

**Comment by tanj1n** [comment]
How can i fix it? After 1st time safe mode i deleted it, i've wanted to re-install it but not working (again in loop)

Pls help :( i love the tweak

**Comment by NoisyFlake** [comment]
> How can i fix it? After 1st time safe mode i deleted it, i've wanted to re-install it but not working (again in loop)
> 
> Pls help :( i love the tweak

Delete the settings .plist file, either through iCleaner or manually through Filza.

I will try to come up with a fix for this for iOS 12.4.

**Comment by tanj1n** [comment]
Really really thank u, is working <3
