### ISSUE TITLE
Compiled deb? 

### ISSUE THREAD

**Issue by foxnoodles** [NoisyFlake/iPadStatusBar#3]
Any way to get the latest version with battery icon crash fixes? ( without having to compile it myself.) Thx

**Comment by NoisyFlake** [comment]
Here you go.

[com.noisyflake.ipadstatusbar_1.1.6_iphoneos-arm.deb.zip](https://github.com/NoisyFlake/iPadStatusBar/files/3994716/com.noisyflake.ipadstatusbar_1.1.6_iphoneos-arm.deb.zip)

**Comment by foxnoodles** [comment]
Thank you!
