### ISSUE TITLE
[Enhancement] Status bar looks bigger in notification center

### ISSUE THREAD

**Issue by s-kk** [NoisyFlake/iPadStatusBar#4]
Hello! 
First, my setup:
Device: iPhone 7 Plus
iOS version: 13.3
Jailbreak: Checkra1n

I've installed the tweak and overall it works well. One small thing is that the status bar icons looks bigger than the system default one (i mean the one without iPadStatusBar installed). I dont need the status bar in lock screen to become iPad styled, but could any updated be done to keep it the way it originally be?

Below are some screenshots.

iOS original notification status bar.  
![IMG_0667](https://user-images.githubusercontent.com/51714930/77739037-d5337980-704b-11ea-91d3-73cbc71dc603.jpg)

Notification status bar with iPadStatusBar installed.  
![IMG_0668](https://user-images.githubusercontent.com/51714930/77739100-ee3c2a80-704b-11ea-8a76-4b8fbb2b66d8.jpg)
The icons and texts are bigger after the installation. And i would like to keep the iOS original size.

Thanks a lot for your effort!

**Comment by Alierya** [comment]
I don't think it will be updated anymore, try iPadBar13:
https://janedut.github.io/repo/
Repair content:
The lock screen status bar is too large
Enabling hidden battery causes safe mode issue
